# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build -t griffin-sdk-docker .
      - ghcr-login

commands:
  ghcr-login:
    description: Login to Github Container Registry
    parameters:
      user:
        description: Name of github user environment variable
        default: GITHUB_USER
        type: env_var_name
      token:
        description: Name of github token environment variable
        default: GITHUB_TOKEN
        type: env_var_name
    steps:
      - run:
          name: Login to GHCR
          command: |
            echo "${<< parameters.token >>}" \
              | docker login ghcr.io -u "${<< parameters.user >>}" --password-stdin

workflows:
  build-container-workflow:
    jobs:
      - build
