# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build -t griffin-sdk-docker .

workflows:
  build-container-workflow:
    jobs:
      - build
