# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t griffin-sdk-docker .
      - ghcr-login
      - push:
        registry: ghcr.io
        image: aatoof1/griffin-sdk-docker
        tag: latest

commands:
  ghcr-login:
    description: Login to Github Container Registry
    parameters:
      user:
        description: Name of github user environment variable
        default: GITHUB_USER
        type: env_var_name
      token:
        description: Name of github token environment variable
        default: GITHUB_TOKEN
        type: env_var_name
    steps:
      - run:
          name: Login to GHCR
          command: |
            echo "${<< parameters.token >>}" \
              | docker login ghcr.io -u "${<< parameters.user >>}" --password-stdin
  push:
    description: Publish image conditionally
    parameters:
      source-registry:
        default: docker.io
        description: Name of source registry to use
        type: string
      registry:
        default: docker.io
        description: Name of registry to use
        type: string
      source-image:
        default: image
        description: Image name
        type: string
      image:
        description: Image name
        type: string
      source-tag:
        default: '${CIRCLE_SHA1}'
        description: Source image tag
        type: string
      tag:
        default: '${CIRCLE_TAG}'
        description: Image tag
        type: string
    steps:
      - tag:
          source-registry: <<parameters.source-registry>>
          target-registry: <<parameters.registry>>
          source-image: <<parameters.source-image>>
          target-image: <<parameters.image>>
          source-tag: <<parameters.source-tag>>
          target-tag: <<parameters.tag>>
      - run:
          name: Publish
          command: >
            docker push
            <<parameters.registry>>/<<parameters.image>>:<<parameters.tag>>

workflows:
  build-container-workflow:
    jobs:
      - build
