# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build -t griffin-sdk-docker .
